//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.16 at 08:31:32 PM EDT 
//


package com.learn.drmodi.model.country;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for country complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="country">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="countryFullName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="countryCapitalName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="countryAlpha3Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="countryPopulation" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "country", propOrder = {
    "countryFullName",
    "countryCapitalName",
    "countryAlpha3Code",
    "countryPopulation",
    "message"
})
public class Country {

    @XmlElement(defaultValue = "")
    protected String countryFullName;
    @XmlElement(defaultValue = "")
    protected String countryCapitalName;
    @XmlElement(defaultValue = "")
    protected String countryAlpha3Code;
    @XmlElement(defaultValue = "0")
    protected Long countryPopulation;
    @XmlElement(defaultValue = "")
    protected String message;

    /**
     * Gets the value of the countryFullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryFullName() {
        return countryFullName;
    }

    /**
     * Sets the value of the countryFullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryFullName(String value) {
        this.countryFullName = value;
    }

    /**
     * Gets the value of the countryCapitalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCapitalName() {
        return countryCapitalName;
    }

    /**
     * Sets the value of the countryCapitalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCapitalName(String value) {
        this.countryCapitalName = value;
    }

    /**
     * Gets the value of the countryAlpha3Code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryAlpha3Code() {
        return countryAlpha3Code;
    }

    /**
     * Sets the value of the countryAlpha3Code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryAlpha3Code(String value) {
        this.countryAlpha3Code = value;
    }

    /**
     * Gets the value of the countryPopulation property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCountryPopulation() {
        return countryPopulation;
    }

    /**
     * Sets the value of the countryPopulation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCountryPopulation(Long value) {
        this.countryPopulation = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

}
