//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.16 at 08:31:32 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://drmodi.learn.com/model/country", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.learn.drmodi.model.country;
